version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: '${PGUSER}'
      POSTGRES_PASSWORD: '${PGPASSWORD}'
      POSTGRES_DB: '${PGDATABASE}'
    ports:
      - '${PGPORT}:${PGPORT}'
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    build: 
      dockerfile: api.Dockerfile
    ports:
      - '${ACICULATE_API_PORT}:${ACICULATE_API_PORT}'
      - '${ACICULATE_API_PORT_SSL}:${ACICULATE_API_PORT_SSL}'
    depends_on:
      - db
    environment:
      PGHOST: '${PGHOST}'
      PGUSER: '${PGUSER}'
      PGDATABASE: '${PGDATABASE}'
      PGPASSWORD: '${PGPASSWORD}'
      PGPORT: '${PGPORT}'
      ACICULATE_USE_SSL: '${ACICULATE_USE_SSL}'
      ACICULATE_APP_PORT: '${ACICULATE_APP_PORT}'
      ACICULATE_APP_PORT_SSL: '${ACICULATE_APP_PORT_SSL}'
      ACICULATE_APP_ORIGIN: '${ACICULATE_APP_ORIGIN}'
      ACICULATE_APP_ORIGIN_SSL: '${ACICULATE_APP_ORIGIN_SSL}'
      ACICULATE_API_PORT: '${ACICULATE_API_PORT}'
      ACICULATE_API_PORT_SSL: '${ACICULATE_API_PORT_SSL}'
      ACICULATE_API_ORIGIN: '${ACICULATE_API_ORIGIN}'
      ACICULATE_API_ORIGIN_SSL: '${ACICULATE_API_ORIGIN_SSL}'
      ACICULATE_API_SSL_KEY_FILEPATH: '${ACICULATE_API_SSL_KEY_FILEPATH}'
      ACICULATE_API_SSL_CERT_FILEPATH: '${ACICULATE_API_SSL_CERT_FILEPATH}'
      ACICULATE_SYSTEM_USER_EMAIL: '${ACICULATE_SYSTEM_USER_EMAIL}'
      ACICULATE_SYSTEM_USER_FIRSTNAME: '${ACICULATE_SYSTEM_USER_FIRSTNAME}'
      ACICULATE_SYSTEM_USER_LASTNAME: '${ACICULATE_SYSTEM_USER_LASTNAME}'
      ACIULCATE_SYSTEM_USER_PASSWORD: '${ACIULCATE_SYSTEM_USER_PASSWORD}'
      ACICULATE_SYSTEM_ORGANIZATION: '${ACICULATE_SYSTEM_ORGANIZATION}'
  app:
    build:
      dockerfile: app.Dockerfile
    ports: 
      - '${ACICULATE_APP_PORT}:${ACICULATE_APP_PORT}'
      - '${ACICULATE_APP_PORT_SSL}:${ACICULATE_APP_PORT_SSL}'
    depends_on:
      - api
    environment:
      ACICULATE_USE_SSL: '${ACICULATE_USE_SSL}'
      ACICULATE_APP_PORT: '${ACICULATE_APP_PORT}'
      ACICULATE_APP_PORT_SSL: '${ACICULATE_APP_PORT_SSL}'
      ACICULATE_APP_ORIGIN: '${ACICULATE_APP_ORIGIN}'
      ACICULATE_APP_ORIGIN_SSL: '${ACICULATE_APP_ORIGIN_SSL}'
      ACICULATE_API_PORT: '${ACICULATE_API_PORT}'
      ACICULATE_API_PORT_SSL: '${ACICULATE_API_PORT_SSL}'
      ACICULATE_API_ORIGIN: '${ACICULATE_API_ORIGIN}'
      ACICULATE_API_ORIGIN_SSL: '${ACICULATE_API_ORIGIN_SSL}'
      ACICULATE_APP_SSL_KEY_FILEPATH: '${ACICULATE_APP_SSL_KEY_FILEPATH}'
      ACICULATE_APP_SSL_CERT_FILEPATH: '${ACICULATE_APP_SSL_CERT_FILEPATH}'
volumes:
  db-data:
    driver: local
